# Generated by Django 2.2.1 on 2019-06-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='操作名称')),
                ('code', models.CharField(max_length=32, verbose_name='查询字符串')),
            ],
            options={
                'verbose_name_plural': '操作',
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='菜单名')),
                ('parent', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sons', to='backend.Menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name_plural': '多级菜单',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='url名称')),
                ('url', models.CharField(max_length=128, verbose_name='url路径')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name_plural': '权限表',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Permission2Action',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Action', verbose_name='操作')),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name_plural': '权限分配操作',
                'db_table': 'permission2action',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': '角色',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User2Role',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Role', verbose_name='角色')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户分配角色',
                'db_table': 'user2role',
            },
        ),
        migrations.CreateModel(
            name='Role2Permission2Action',
            fields=[
                ('nid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p2a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Permission2Action', verbose_name='权限+动作')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name_plural': '角色分配(权限+操作)',
                'db_table': 'Role2Permission2Action',
            },
        ),
    ]
